# Automatically generated by Honest Code
# Do not edit this file as it will be overwritten

@android
Feature: Access to news detail
  as an user
  I want to see a news detail

  Scenario: Show a list of news
    Given User is on news list and data is ok
    When User click on a valid news in the list
    Then A detail screen is showed


