# Automatically generated by Honest Code
# Do not edit this file as it will be overwritten

@android
Feature: As an user, i want to load from net a list of news

  Scenario: Load news from net
    Given Load news from net and data is ok
    Then A list of news is returned